<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE productos [

   <!ELEMENT productos (producto)*>

   <!ELEMENT producto (identificacion, nombre)>

   <!ELEMENT identificacion (#PCDATA | codigo | id)*>

   <!ELEMENT codigo (#PCDATA)>

   <!ELEMENT id (#PCDATA)>

   <!ELEMENT nombre (#PCDATA)>

]>

<productos>
    <producto>
    <!-- primero es identificacion y luego nombre -->    
   <!--  <nombre>martillo</nombre> -->
    
         <identificacion>
        
             Quedan 14 unidades.
        
            <codigo>MAR264</codigo>
        
         </identificacion>
         <nombre>Matillo</nombre>
    </producto>
    
    <!-- ANtes de repetir identificacion, que se puede,
    hay que poner el nombre si o si porque hay que seguir
    el orden-->
    <producto>
         <identificacion>
        
             <codigo>DES387</codigo>
        
              <id>678984</id>
        
              No hay stock.
             <!-- no puede estar dentro de identificacion -->
             <!-- <nombre>destornillador</nombre> -->
        
          </identificacion>
        <nombre>Escalera</nombre>
    </producto>
    
</productos>