<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE saludos [

   <!ELEMENT saludos (saludo*)>

   <!ELEMENT saludo (#PCDATA)>

      <!ATTLIST saludo idioma (ALE | FRA | ITA | POR) #IMPLIED>

]>
<!-- en los atributos hay que ponerlo dentro del parentesis, y si
añadir #loqueseanecesario, no ponemos ID porque sino es obligatorio-->
<saludos>
    
    <saludo idioma="ALE">Hallo</saludo>
    
    <saludo>Hola</saludo>
    
    <saludo idioma="ITA">Ciao</saludo>
    
    <saludo idioma="FRA">Salut</saludo>
    
    <saludo idioma="POR">Olá</saludo>
    
</saludos>